trigger:
  branches:
    include:
      - 'release/*'
    exclude:
      - 'release/v3'

pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: '0 * * * *'
    displayName: Daily build
    branches:
      include:
        - main
        - 'release/*'
      exclude:
        - 'release/v3'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'