trigger: none

pool: my-pc

schedules:
  - cron: '0 * * * *'
    displayName: Daily build
    branches:
      include:
      - new-branch-100
    always: true

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'