trigger:
- main

pool: pc

schedules:
  - cron: '0 * * * *'
    displayName: Daily build
    branches:
      include:
      - main
    always: true

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'