trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

pr: none

resources:
  repositories:
    - repository: testrepo
      type: github
      name: nat-borisova/test1
      endpoint: GitHub
      ref: refs/heads/main 

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'