trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

pr: none

resources:
  repositories:
    - repository: nat-borisova
      type: github
      endpoint: GitHub
      name: test1
      ref: refs/heads/master  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'