trigger: none

pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: '0 * * * *'
    displayName: Hourly build
    branches:
      include:
        - main
        - release/*
      exclude:
        - release/v3
    always: true

  - cron: '0 */2 * * *'
    displayName: Every 2 hours build
    branches:
      include:
        - release/*
    always: true

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'