trigger: none

pool:
  vmImage: 'ubuntu-latest'

schedules:
  - cron: '0 */2 * * *'
    displayName: Every 2 hours build
    branches:
      include:
        - deploy/v1
      exclude:
        - deploy/v2
    always: true

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'